name: Deploy Staging to VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no captrit-admin@<your-vps-ip> << 'EOF'
            cd ~/apps/captrit-staging
            git pull origin staging
            npm install
            npm run build
            PORT=3001 pm2 restart captrit-staging || PORT=3001 pm2 start npm --name "captrit-staging" -- start
          EOF
