name: Deploy to VPS on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no captrit-admin@82.29.165.100 << 'EOF'
          cd ~/apps/captrit-main
          git reset --hard
          git pull origin main
          npm install
          npm run build
          pm2 restart captrit
        EOF
